In [1]:
import pandas as pd

df = pd.read_csv("Project/IPL.csv")
print(df.shape)
(20,6)

(74, 20)

(20, 6)

In [2]:
print(df.dtypes)

match_id               int64
date                     str
venue                    str
team1                    str
team2                    str
stage                    str
toss_winner              str
toss_decision            str
first_ings_score       int64
first_ings_wkts        int64
second_ings_score      int64
second_ings_wkts       int64
match_winner             str
won_by                   str
margin                 int64
player_of_the_match      str
top_scorer               str
highscore              int64
best_bowling             str
best_bowling_figure      str
dtype: object

In [3]:
print(df.head())

   match_id           date                                         venue  \
0         1  March 26,2022                      Wankhede Stadium, Mumbai
1         2  March 27,2022                     Brabourne Stadium, Mumbai
2         3  March 27,2022            Dr DY Patil Sports Academy, Mumbai
3         4  March 28,2022                      Wankhede Stadium, Mumbai
4         5  March 29,2022  Maharashtra Cricket Association Stadium,Pune

       team1      team2  stage toss_winner toss_decision  first_ings_score  \
0    Chennai    Kolkata  Group     Kolkata         Field               131
1      Delhi     Mumbai  Group       Delhi         Field               177
2   Banglore     Punjab  Group      Punjab         Field               205
3    Gujarat    Lucknow  Group     Gujarat         Field               158
4  Hyderabad  Rajasthan  Group   Hyderabad         Field               210

   first_ings_wkts  second_ings_score  second_ings_wkts match_winner   won_by  \
0                5                133                 4      Kolkata  Wickets
1                5                179                 6        Delhi  Wickets
2                2                208                 5       Punjab  Wickets
3                6                161                 5      Gujarat  Wickets
4                6                149                 7    Rajasthan     Runs

   margin player_of_the_match      top_scorer  highscore      best_bowling  \
0       6         Umesh Yadav        MS Dhoni         50      Dwayne Bravo
1       4       Kuldeep Yadav    Ishan Kishan         81     Kuldeep Yadav
2       5         Odean Smith  Faf du Plessis         88    Mohammed Siraj
3       5      Mohammed Shami    Deepak Hooda         55    Mohammed Shami
4      61        Sanju Samson   Aiden Markram         57  Yuzvendra Chahal

  best_bowling_figure
0               3--20
1               3--18
2               2--59
3               3--25
4               3--22

In [4]:
df.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
3,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,161,5,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,149,7,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22

In [5]:
df.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,margin,highscore
count,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000
mean,37.500000,171.121622,6.135135,158.540541,6.175676,16.972973,71.716216
std,21.505813,29.048355,2.222699,29.299207,2.639832,19.651047,20.705052
min,1.000000,68.000000,0.000000,72.000000,1.000000,2.000000,28.000000
25%,19.250000,154.250000,5.000000,142.750000,4.000000,5.250000,57.000000
50%,37.500000,169.500000,6.000000,160.000000,6.000000,8.000000,68.000000
75%,55.750000,192.750000,8.000000,176.000000,8.000000,18.000000,87.750000
max,74.000000,222.000000,10.000000,211.000000,10.000000,91.000000,140.000000