In [3]:
import numpy as np
import pandas as pd

Creating a dataFrame

In [4]:
data = {
    'Name': ['Shiv', 'Raj', 'Ram', 'John'],
    'Age': [21, 23, 46, 43],
    'City': ['GKP', 'Delhi', 'Mumbai', 'Bangluru'],
    'Salary': [50000, 60000, 30000, 40000]
}
df = pd.DataFrame(data)

In [5]:
df

   Name  Age      City  Salary
0  Shiv   21       GKP   50000
1   Raj   23     Delhi   60000
2   Ram   46    Mumbai   30000
3  John   43  Bangluru   40000

In [6]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 23, 'Peris', 75000],
    ['Peter', 38, 'Berlin', 45000],
    ['Linda', 30, 'London', 60000],
]

df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns  =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

In [7]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

Selection and Indexing of columns

In [8]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

In [9]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [10]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Peris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [11]:
df2["Designation"] = ["Doctor", "Eng", "Lawyer", "Business"]

In [12]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   23     Peris   75000         Eng
2  Peter   38    Berlin   45000      Lawyer
3  Linda   30    London   60000    Business

Removing Columns

In [13]:
df2.drop(['Designation'], axis =1, inplace=True)

In [14]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

In [15]:
df2.drop(['City', 'Salary'], axis = 1)

    Name  Age
0   John   28
1   Anna   23
2  Peter   38
3  Linda   30

In [16]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

In [17]:
df2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   23   Peris   75000
2  Peter   38  Berlin   45000
3  Linda   30  London   60000

Selecting Rows

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

In [19]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   23     Peris   75000

Selecting Subsets of Rows and Columns

In [20]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Peris   75000

Conditional Selectin

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   23     Peris   75000
2  Peter   38    Berlin   45000
3  Linda   30    London   60000

In [31]:
df2[df2["Age"] < 30]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   23     Peris   75000

In [35]:
df2[(df2["Age"] < 30) & (df2["City"] == "Peris")]

   Name  Age   City  Salary
1  Anna   23  Peris   75000